### ISSUE TITLE
Pseudo R² calculations

### ISSUE THREAD

**Issue by cschwem2er** [sjPlot/sjstats#10]
Hi,

I just tried to refit a negative binomial model from Stata in R to see whether the coefficients are the same.

````
reg2 <- glm.nb(comments_count_fb ~ maxprop + day, data = d)

````
The coefficients are in line:

![image](https://user-images.githubusercontent.com/7460499/27760954-8d86e390-5e53-11e7-989a-a1f5a871d538.png)

![image](https://user-images.githubusercontent.com/7460499/27760944-682154e6-5e53-11e7-8e24-17dfba23c210.png)

But what I realized is that there is a huge difference in the numbers for the Pseudo R²s:
![image](https://user-images.githubusercontent.com/7460499/27760963-b8f61226-5e53-11e7-90ae-5bd5c48911b6.png)

Is it possible that the formulas in sjstats are not correct? I found the code in `sjstats:::pseudo_ralt`:
````
  CoxSnell <- 1 - exp((stats::deviance(x) - x$null.deviance)/n)
  Nagelkerke <- CoxSnell/(1 - exp(-x$null.deviance/n))
````
Wikipedia lists these formulas (based on log-likelihood):

![image](https://user-images.githubusercontent.com/7460499/27761017-9b756264-5e54-11e7-8b59-1955af4fffb5.png)

![image](https://user-images.githubusercontent.com/7460499/27761019-a1c0aff2-5e54-11e7-8631-280f4f903c4c.png)

And the Stata code in the background looks like this:
````
* ML R2 Cox-Snell
cap scalar `r2_ml' = 1 - exp(2*(`ll_0'-`ll')/`N')
* Cragg-Uhler R2
cap scalar `r2_cu' = (`r2_ml')/(1-exp(2*`ll_0'/`N'))
````
where ``ll_0`` is the log-likelihood of the null model and ``ll`` the log-likelihood.

If I use the `nagelkerke` function from the package [rcompanion](https://cran.r-project.org/web/packages/rcompanion/index.html), I get the same numbers as in Stata:
````
rcompanion::nagelkerke(reg2)
$Models
                                                                       
Model: "glm.nb, comments_count_fb ~ maxprop + day, d, 1.327074476, log"
Null:  "glm.nb, comments_count_fb ~ 1, d, 0.9229716263, log"           

$Pseudo.R.squared.for.model.vs.null
                             Pseudo.R.squared
McFadden                            0.0332483
Cox and Snell (ML)                  0.3660860
Nagelkerke (Cragg and Uhler)        0.3660860
````
  This is a code snippet from the `nagelkerke()` function:

```

    m = suppressWarnings(logLik(fit, REML = FALSE))[1]
    n = suppressWarnings(logLik(null, REML = FALSE))[1]
    cs = 1 - exp(-2/N * (m - n))
    nk = cs/(1 - exp(2/N * n))
```

**Comment by strengejacke** [comment]
Yes, r2 for count models is not properly implemented yet. As you may have seen in the source (https://github.com/strengejacke/sjstats/blob/master/R/pseudo_r2.R#L263), there is some out-commented code that should do that, but I was unsure about the correct formula. But thanks for your tipps, I will implement support for count models based on your suggestions.

**Comment by strengejacke** [comment]
btw, don't use Pseudo-R2-values (i.e. r2 for glm's)! ;-)

**Comment by cschwem2er** [comment]
I hate it as well.. but sometimes I collaborate with scientists in fields where this is "standard".
