### ISSUE TITLE
object 'null_model'

### ISSUE THREAD

**Issue by thuyvyn** [sjPlot/sjstats#101]
Hi,

I try to use the ICC function from sjstats, but it keeps showing up the error:

Error: package or namespace load failed for ‘sjstats’:
 object ‘null_model’ is not exported by 'namespace:insight'

When I downloaded the developer version, using: 
library(devtools)
devtools::install_github("strengejacke/sjstats")

It shows the following error:
Error: Failed to install 'sjstats' from GitHub: System command error, exit status: 1, stdout + stderr (last 10 lines): E> ** R E> ** data E> ** inst E> ** byte-compile and prepare package for lazy loading E> Error: object ‘null_model’ is not exported by 'namespace:insight' E> Execution halted E> ERROR: lazy loading failed for package ‘sjstats’ E> * removing ‘/private/var/folders/qy/n4rfmd9x41lfw1vxrd95ck5c0000gp/T/RtmpIq1XkS/Rinst53aa61eba566/sjstats’ E> ----------------------------------- E> ERROR: package installation failed

**Comment by strengejacke** [comment]
You need to update the _insight_ package. The `icc()` function is now living in the [performance-package](https://easystats.github.io/performance), however, you still can use `sjstats::icc()`, as it internally just calls `performance::icc()`.
