### ISSUE TITLE
CV for mixed models is valid?

### ISSUE THREAD

**Issue by SchmidtPaul** [sjPlot/sjstats#109]
In the [R² vigniette](https://easystats.github.io/performance/articles/r2.html#different-types-of-r2) of {performance} it is written that "*As models become more complex, the computation of an R2 becomes increasingly less straightforward.*"

Shouldn't this whole topic also be true for the coefficient of variation? Don't get me wrong - I was happy to find a function that would get me a CV for `merMod`/`lme` class objects. At the same time I was skeptical whether it is valid to [simply get the RMSE](https://github.com/strengejacke/sjstats/blob/19b3deae4ad1d0c5ec072a40d6be02f566d709d4/R/cv.R#L48) from any mixed model accounting for heteroscedasticity and for covariance among observations present in residual error.

Please correct me if I'm wrong - I'd simply like your thoughts on this.

**Comment by strengejacke** [comment]
Yes, it's _probably_ not accurate for mixed models (depending on whether we get accurate residuals). Though there are other packages that also compute the RMSE for mixed models (_merTools_ e.g.), and the CV is just the scaled RMSE

**Comment by SchmidtPaul** [comment]
Alright, thanks!
