### ISSUE TITLE
rse and std_beta functions not found

### ISSUE THREAD

**Issue by gtobin26** [sjPlot/sjstats#113]
I have standard multiple regression in which the fit is named lmgeall.

rmse(lmgeall) works fine
> print(rmse)
[1] 0.5281803

But for both rse and std_beta, I get error messages, e.g.
rse(lmgeall)
Error in rse(lmgeall) : could not find function "rse"

Previously when I tried to install the independent package std_beta from CRAN, I got an error message that it was not available on the current version of R. Perhaps that is the underlying problem? I am using 4.1.2 (2021-11-01).

Regards,

Graham

**Comment by strengejacke** [comment]
The _sjstats_ package has been restructured, and many functions been re-implemented in the [easystats-ecosystem](http://easystats.github.io/easystats) of R packages.

You find most functions in the [performance-package](https://easystats.github.io/performance/), e.g. also [`performance_rse()`](https://easystats.github.io/performance/reference/performance_rse.html). All parameter-/coefficient-related stuff is in the [parameters-package](https://easystats.github.io/parameters/) now, e.g. [`standardize_parameters()`](https://easystats.github.io/parameters/reference/standardize_parameters.html). A detailed documentation for the latter can be found [here](https://easystats.github.io/parameters/articles/model_parameters_standardized.html).

**Comment by gtobin26** [comment]
Thanks for the fast response and excellent advice. I was able to obtain the standardized regression coefficients and their ci following your recommendation.
