### ISSUE TITLE
Could not find function "weighted_ttest"

### ISSUE THREAD

**Issue by appariciop** [sjPlot/sjstats#122]
Dear Daniel,
The weighted_ttest function no longer seems to be available in sjstats 0.19.0, unlike in version 0.18.2.
Best regards,
Philippe

**Comment by strengejacke** [comment]
The tests have been renamed and the code was re written to be more consistent. See https://strengejacke.github.io/sjstats/reference/index.html#significance-tests

For weighted tests, the functions now simply have a `weights` argument.

**Comment by appariciop** [comment]
Wonderful! Thank you for your prompt reply!
Philippe
