### ISSUE TITLE
Why am i still not getting sjstats 11.0?

### ISSUE THREAD

**Issue by cathytao** [sjPlot/sjstats#14]
I am hoping to install sjPlot but sjstats seems to remain 10.1 version. How to get 11.0?

> library(sjstats)
> update.packages("sjstats")
> library(sjPlot)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘sjstats’ 0.10.1 is being loaded, but >= 0.11.0 is required
Error: package or namespace load failed for ‘sjPlot’

**Comment by sjPlot** [comment]
After starting R(Studio), don't load the library, but install the update first (`install.packages("sjstats", dependencies = TRUE)`).

It could also be that you have an R version < 3.3.3 - sjstats depends on sjmisc and sjlabelled, and sjlabelled in turn depends on the snakecase pkg - which depends on R >= 3.3.3. I'm in contact with the pkg maintainer to see that dependency can be changed to R >= 3.2

**Comment by strengejacke** [comment]
Else, I probably re-submit sjlabelled and make it only suggest snakecase, not depend on it.

**Comment by cathytao** [comment]
Thank you @strengejacke it works!
