### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by aranglancy** [sjPlot/sjstats#15]
I'm trying to install this package (Max OS X, R v. 3.4.2, RStudio v. 1.1.383) and I keep getting the error:

     installation of package ‘sjstats’ had non-zero exit status

The source of the problem seems to be with the TMB and Matrix packages?

Warning in checkMatrixPackageVersion() :
  Package version inconsistency detected.
TMB was built with Matrix version 1.2.10
Current Matrix version is 1.2.11
Please re-install 'TMB' from source or restore original 'Matrix' package
Error : object ‘modify_if’ is not exported by 'namespace:purrr'
ERROR: lazy loading failed for package ‘sjstats’

**Comment by strengejacke** [comment]
I guess it's due to an older version of the purrr-package. Could you try to update purrr first?

**Comment by aranglancy** [comment]
Thanks! That fixed it.
