### ISSUE TITLE
Error message re: sjt.glmer?

### ISSUE THREAD

**Issue by cathytao** [sjPlot/sjstats#16]
> library("sjPlot")
> library(sjstats)
> library(sjlabelled)
> sjt.glmer(p0)
**Error in object@pp$unsc() : object 'merPredDunsc' not found**

After fitting my glm model, and installed all required packages, I got that error message, how to resolve it?

**Comment by strengejacke** [comment]
Do you have a reproducible example? From this error message, I can't see if it's an issue of any of my packages or not.

**Comment by cathytao** [comment]
For unknown reason, it is no longer an issue; did not do anything further...thanks though!

**Comment by strengejacke** [comment]
ok, thanks!
