### ISSUE TITLE
anova effect size function not working with 

### ISSUE THREAD

**Issue by IndrajeetPatil** [sjPlot/sjstats#18]
Hi,

If I set the argument of `car::Anova` (https://goo.gl/DBpMim) `TRUE`, so that we have a heteroscedasticity-corrected coefficient covariance matrix while computing ANOVA summary, I can't seem to get the partial eta-squared by `sjstats::eta_sq(aov, partial = TRUE)`.

As you noted in your response on Twitter-
"The problems seems to be that when using `white.adjust = TRUE`, then neither `as.data.frame()` nor `broom::tidy()` return the sums of squares, which is needed to compute eta squared."

Thanks for any help you might offer.

**Comment by strengejacke** [comment]
Probably, this is in first instance something to be solved from the maintainers of the *car* package?

**Comment by IndrajeetPatil** [comment]
Okay, cool. I will open this issue at `car` package.

**Comment by IndrajeetPatil** [comment]
I had raised this issue with the `car` package maintainer and here is what he wrote me back-

> If you use an adjusted covariance matrix for the tests then there aren't SSs in the usual sense corresponding to the ANOVA table, which is why Anova() doesn't compute or print them.

So I guess this is just no way around this problem. 

You can close this issue if you want. Thanks!

**Comment by strengejacke** [comment]
Ok, good to know! Thanks for going deeper into this issue!
