### ISSUE TITLE
effect sizes on non-significant p-values

### ISSUE THREAD

**Issue by ImmanuelSamuel** [sjPlot/sjstats#19]
Currently package returns NA for effect sizes where p>0.05. Is there a way to view the etasq when p>0.05?

**Comment by strengejacke** [comment]
Which function do you refer to? Do you have a reproducible example?

**Comment by ImmanuelSamuel** [comment]
OK I was able to figured it out. In aov_stats_core nterms = total -1. The last one was the interaction term. However this still doesn't work for lmer because that doesn't have a 'sumsq' in the summary table. Any idea  on how to solve that?

**Comment by strengejacke** [comment]
The functions only work for Anovas, not for "plain" regressions.
