### ISSUE TITLE
`se()` not working for merMod with specific random parts

### ISSUE THREAD

**Issue by sjPlot** [sjPlot/sjstats#2]
I am trying to plot the joint random and fixed effects coefficients for each level of each grouping variable (actually, I am only interested in one grouping variable). I have three grouping vars with 948, 8, and 6 levels. Calling the function produces only one plot (for the grouping var with 948 levels) and the following errors and warnings:

sjp.lmer(mlm3, type="coef")
Error in [.data.frame(se.fit, , i) : undefined columns selected

In addition: Warning messages:
1: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS does not recycle exactly across MARGIN
2: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS is longer than the extent of 'dim(x)[MARGIN]'
3: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS does not recycle exactly across MARGIN
4: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS does not recycle exactly across MARGIN
5: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS is longer than the extent of 'dim(x)[MARGIN]'
6: In sweep(cmode.vars, 2, fixed.vars, "+") :
STATS does not recycle exactly across MARGIN

(see _data_and_model.RData_)

**Comment by favstats** [comment]
So this isn't resolved yet, is it?

**Comment by strengejacke** [comment]
No, not yet. I think, setting `show.ci = FALSE` should work, but of course, w/o confidence intervals then. I had not yet found the time to investigate this issue further.

**Comment by GitDro** [comment]
Is this related to se() not working on icc objects? Because I find that se(icc(fit)) returns an NA even on the example vignette with sjstats 0.17.1, R version 3.5.1

**Comment by strengejacke** [comment]
> Is this related to se() not working on icc objects? Because I find that se(icc(fit)) returns an NA even on the example vignette with sjstats 0.17.1, R version 3.5.1

No, but this issue should be fixed with https://github.com/strengejacke/sjstats/commit/010310f0b6c19c080353d7732292ab7ce4507ddd
