### ISSUE TITLE
effect size calculation for repeated measures anova?

### ISSUE THREAD

**Issue by ereverman** [sjPlot/sjstats#20]
Is there a way to calculate Cohen's F and other effect size functions for a repeated measures anova, which, using aov, can't be coerced to an aov object? 

Thanks,
Elizabeth

**Comment by strengejacke** [comment]
do you have an example, or even a reproducible example?

**Comment by ereverman** [comment]
Sure, an example is below. Thanks for looking into this.

```r
library(sjstats)

# Make up data. Repeated measure of response across 10 periods:
dat<-data.frame(trt=c(rep("L",50),rep("D",50)), period=rep(1:10, 10), response=c(sample(100:200, 50, replace=TRUE),sample(50:150, 50, replace=TRUE)))

# Regular ANOVA, effect size function works great:
reg.aov<-anova(aov(response~trt*as.factor(period), data=dat))
cohens_f(reg.aov)

# Repeated measures ANOVA:
rep.aov<-aov(response~trt + Error(as.factor(period)), data=dat)
summary(rep.aov)
anova(rep.aov) # Can't use anova on the output because it is in a list format

cohens_f(summary(rep.aov)) # Can't calculate the effect sizes because the initial list format can't be coerced into anova format, which if I'm understanding correctly, is required for the function
```

**Comment by strengejacke** [comment]
Should be working now, but requires broom >= 0.4.5

**Comment by ereverman** [comment]
Thanks for the update, although using broom 0.4.5, I can't tidy the anova output from my example. This seems to be a bug with broom. Can you share how you made it work?

Elizabeth

**Comment by strengejacke** [comment]
```r
rep.aov<-aov(response~trt + Error(as.factor(period)), data=dat)
cohens_f(rep.aov)
#> # A tibble: 2 x 2
#>   term      cohens.f
#>   <chr>        <dbl>
#> 1 Residuals    0.278
#> 2 trt          0.919
```

**Comment by ereverman** [comment]
Here is my output from the same thing:

rep.aov<-aov(response~trt + Error(as.factor(period)), data=dat)
cohens_f(rep.aov) 
Error in UseMethod("anova") : 
  no applicable method for 'anova' applied to an object of class "c('aovlist', 'listof')"

**Comment by strengejacke** [comment]
Have you updated sjstats from GitHub? There is no Update on cran yet.

**Comment by ereverman** [comment]
I installed with:
install_github("strengejacke/sjstats")
library(sjstats)

Version number is 0.15.0.9000. broom version is 0.4.5.

Now running the same code, I get a slightly different error:

cohens_f(rep.aov) 
Error in if (attr(object$terms, "intercept")) table <- table[-1, ] : 
  argument is of length zero

I tried running the example in #34 and am getting the same error.

**Comment by strengejacke** [comment]
True, you actually need the current GitHub-version of _broom_. Though broom 0.4.5 was just released on CRAN, there are obviously some more changes in the current GitHub version. Furthermore, for CI, you need the latest changes in sjstats, which are not commited yet. Try re-installing sjstats from GitHub tomorrow, and everything should work.
