### ISSUE TITLE
Feature request: confidence intervals for sjstats::eta_sq

### ISSUE THREAD

**Issue by IndrajeetPatil** [sjPlot/sjstats#21]
I was wondering if it would be possible to also include confidence intervals (CI) for the effect sizes provided by `sjstats::eta_sq`. There are some other packages that do provide this. For example, CI for- 

- `omega_squared` can be obtained with `userfriendlyscience::confIntOmegaSq` 
- `partial_eta_squared` can be obtained with `apaTables::get.ci.partial.eta.squared`

But I am a bit wary of utilizing so many packages and mixing different pieces of results from varied packages together, so it'd be really nice to have all of the necessary statistical details from the same package itself.

**Comment by strengejacke** [comment]
I'd be happy for a PR or any hints on how to compute CI for eta squared and probably Cohen's F?

**Comment by Deleetdk** [comment]
Some time ago, I was trying to determine this as well. It seems to be difficult because they are non-symmetric (like those for Pearson r) so one probably has to transform to an intermediate metric, calculate and transform back. Might be hard, so bootstrapping is likely a better option.

**Comment by strengejacke** [comment]
So, something like:

```r
library(tidyverse)
library(sjstats)
data(efc)

eta_sq(aov(c12hour ~ as.factor(e42dep), data = efc))
#> as.factor(e42dep) 
#>         0.2447745

efc %>%
  bootstrap(n = 100) %>%
  mutate(eta_squared = map_dbl(
    strap,
    ~ eta_sq(aov(c12hour ~ as.factor(e42dep), data = .x))
  )) %>%
  boot_ci(eta_squared)
#>          term  conf.low conf.high
#> 1 eta_squared 0.1937184 0.2989899
```

**Comment by IndrajeetPatil** [comment]
Yeah, that works! Also, the results are pretty close to what you get with `apaTable`, which doesn't use bootstrapping.

``` r
library(sjstats)
library(apaTables)
data(efc)

# model
mod.sum <- unlist(summary(stats::aov(c12hour ~ as.factor(e42dep), data = efc)))

# CI for partial eta-squared
apaTables::get.ci.partial.eta.squared(F.value = mod.sum["F value1"][[1]],
                                      df1 = mod.sum["Df1"][[1]],
                                      df2 = mod.sum["Df2"][[1]],
                                      conf.level = 0.95)
#> $LL
#> [1] 0.1970615
#> 
#> $UL
#> [1] 0.2882962
```

Created on 2018-03-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by strengejacke** [comment]
ok, bootstrap for `eta_sq()` is included. Does the same approach apply to Cohen's F, or are CI nonsense in that case?

**Comment by Deleetdk** [comment]
Bootstrapping generally works for every metric you can think of, but resampling may be difficult in some designs e.g. if you have nested data.

Note that eta^2 is actually a quite biased metric, so it would be wise to default to using omega^2 (or epsilon^2). See:

- http://daniellakens.blogspot.nl/2015/06/why-you-should-use-omega-squared.html

You can get CIs for these using bootstrapping too.

My current statistical issue is that I want to calculate omega^2 for complex models fit using `rms::ols`, but it seems that none of the standard approaches allow for using type 2 sums of squares. See:

- https://github.com/harrelfe/rms/issues/60

If you made your main functions S3 generics, you could add support for ANOVA fits no matter whether they are from `stats::aov`, `stats::anova`, `car::Anova` or `rms::ols.anova`.

**Comment by strengejacke** [comment]
anova()-objects from *rms*  should work now:

```
ols(Sepal.Width ~ Petal.Width, data = iris) %>%
  anova() %>% 
  omega_sq(ci.lvl = .95)

#> # A tibble: 2 x 4
#>   term        omega_sq conf.low conf.high
#>   <chr>          <dbl>    <dbl>     <dbl>
#> 1 Petal.Width    0.112   0.0475     0.235
#> 2 TOTAL          0.112   0.0475     0.235
```

**Comment by strengejacke** [comment]
Is there a way to obtain CI for _partial_ omega-squared? I implemented the partial-option for omega-squared based on this formula:
https://1.bp.blogspot.com/-99Qe57qODA4/Vaz1o5Q_cdI/AAAAAAAACrk/kaxJ_PG7VeU/s400/eta%2Bomega.png

**Comment by strengejacke** [comment]
Ok, if someone knows how to compute CI for partial omega-squ. _without_ using bootstrapping, pls let me know. Furthermore, can someone confirm that `eta_sq()` and `omega_sq()` return the same results as, e.g. other software packages like SPSS or so?

- [ ] CI for partial omega
- [ ] validate code for calculating effect sizes

**Comment by IndrajeetPatil** [comment]
I've used `iris` dataset with the following formula: `Sepal.Length ~ Species` and can confirm that the output of `eta_sq()` and `omega_sq()` match with those from other software, like ` jamovi` and `JASP`.

With `sjstats`:
![image](https://user-images.githubusercontent.com/11330453/37560362-d7944984-2a0c-11e8-8a83-43aac5719c46.png)

These are the results from `jamovi` software (https://www.jamovi.org/download.html):
![image](https://user-images.githubusercontent.com/11330453/37560075-e62ab74e-2a07-11e8-9d0f-1c4d2bf28316.png)

These results are from `JASP` software:
![image](https://user-images.githubusercontent.com/11330453/37560187-5790a554-2a0a-11e8-9bbc-ee6dae7e855d.png)

For one-way ANOVA, SPSS doesn't provide any effect size measure.

Partial omega-squared is not implemented in any of these software (I don't have `stata`, but it _might_ be implemented there) and **none** of them provide confidence intervals for any of the effect size measures, so that's a major plus for `sjstats`! :)

I will work on validating the code now. I will also cross-reference these computations with Borenstein's book on effect sizes.

**Comment by IndrajeetPatil** [comment]
@strengejacke @sjPlot Thanks for including this functionality! My package now imports `sjstats` and relies on these new functions :)
https://cran.r-project.org/web/packages/ggstatsplot/index.html

I was wondering if it would be possible to include similar bootstrapped confidence intervals for `phi` function in the future releases of `sjstats`:
Cramer's _V_, Phi, Spearman’s _rho_, Kendall’s _tau_, and Pearson’s _r_

**Comment by theogeneserich** [comment]
Dear all,

I am a bit confused about a result I am getting as Output of:
sjstats::eta_sq(model1, partial = TRUE, ci.lvl = .95)
it gives me a partial.etasq of 0.955, conf.low of 0,193 and conf.high of 0.501.
My confusion is, because the conf.high is lower than the partial.etasq for that effect. I get the same results when I use another R-package (MBESS):
Lims <- conf.limits.ncf(F.value = 15.4105982, conf.level = 0.95, df.1 <- 3, df.2 <- 75)
Lower.lim <- Lims$Lower.Limit/(Lims$Lower.Limit + df.1 + df.2 + 1)
Upper.lim <- Lims$Upper.Limit/(Lims$Upper.Limit + df.1 + df.2 + 1)

Can you help me out here?
Thanks in advance!

**Comment by theogeneserich** [comment]
Dear all,

I just realized that I haven't specified my model. So maybe that helps:

model1 <- aov(Rating ~ (repfac1*repfac2) + Error(vid/(repfac1*repfac2)), contrasts = contr.sum, data = data_repeated_measure)
sjstats::eta_sq(model1, partial = TRUE, ci.lvl = .95)
it gives me a partial.etasq of 0.955, conf.low of 0,193 and conf.high of 0.501

Further I get an error message when trying to calculate the confidence interval for partial=FALSE:
sjstats::eta_sq(model1, partial = FALSE,  ci.lvl = .95)
"Error in cbind_all(x) : Argument 2 must be length 6, not 13"

**Comment by strengejacke** [comment]
Please open a new issue so I can keep track of it.

**Comment by theogeneserich** [comment]
#39
