### ISSUE TITLE
Offsets not being used

### ISSUE THREAD

**Issue by eborgnine** [sjPlot/sjstats#26]
Hello.  If I put offsets in my formula they aren't being passed to glm.nb, see example below.  seems the svymle function ignores offsets.   

Is this a problem for the survey package?  or could sjstats_loglik et al be modified to include an offset argument?

```
mydat = data.frame(
    y = sample(1:10),
    x = seq(-1,1,len=10),
    weights = rep(1, 10),
    myoffset = 20
    )
    
glm(y ~ x + offset(myoffset), data = mydat, family='poisson')$coef
MASS::glm.nb(y ~ x + offset(myoffset), data=mydat)[
    c('theta', 'coefficients')]

sjstats::svyglm.nb(
    y ~ x + offset(myoffset),
    design = survey::svydesign(
        ids = ~1, weights = ~ weights,
        data = mydat)
)$estimate
```

**Comment by strengejacke** [comment]
I'm not sure if and where to consider the offset. `sjstats_loglik()` gets the formulas via the `eta`-argument, so inside the formula, the offset should be concluded. But I'm not sure what `svymle()` does internally. Maybe there's a way to explicitly take the offset in `sjstats_loglik()` into account?

**Comment by eborgnine** [comment]
svymle is getting rid of the offsets in the formula, for some reason.  the ideal solution would be for svymle to retain the offset part of the formula. I'll write the maintainers of the survey package.

another solution would be to have an offset argument to svyglm.nb, which would default to a vector of 1's.  svyglm.nb would pass the offsets to sjstats_loglik.

**Comment by strengejacke** [comment]
So, should I close this, as @tslumley addreses this issue, or try to implement a workaround until the _survey_-pkg is updated? (I would prefer the first option to avoid interference once the survey pkg is updated and sjstats still has its workaround).

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
I just saw that the update of the survey-package allows offset in `svymle()` - does this solve this issue?
