### ISSUE TITLE
Robust standard errors

### ISSUE THREAD

**Issue by cschwem2er** [sjPlot/sjstats#3]
Hi, is there currently a function to provide robust standard errors (and CI's, p-values) for regression results? In Stata using the option ``robust`` after a regression does all the work. From what I understand at the moment, in R one has to calculate it manually via the ``sandwich`` package and then write additional functions to create an adjusted ``summary``.

**Comment by sjPlot** [comment]
What would be the expected Output? Coefficients, se and ci?

**Comment by cschwem2er** [comment]
Yes, I think the easiest way to do this is by using ```lmtest::coeftest```and ``sandwich::vcovHC``:

````
install.packages(c('lmtest','sandwich'))

set.seed(1)
x <- runif(500, 0, 1)
y <- 5 * rnorm(500, x, x)

reg1 <- lm(y~x)
summary(reg1)

############################################
Call:
lm(formula = y ~ x)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.1714  -1.2699  -0.1496   1.3075   9.3736 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   0.2592     0.2732   0.949    0.343    
x             4.2414     0.4786   8.862   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.029 on 498 degrees of freedom
Multiple R-squared:  0.1362,	Adjusted R-squared:  0.1345 
F-statistic: 78.53 on 1 and 498 DF,  p-value: < 2.2e-16
###############################################

lmtest::coeftest(reg1, vcov = sandwich::vcovHC(reg1,type="HC1"))

#################################################
t test of coefficients:

            Estimate Std. Error t value  Pr(>|t|)    
(Intercept)  0.25920    0.18196  1.4246    0.1549    
x            4.24137    0.53851  7.8761 2.134e-14 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
###################################################
````
I adjusted this code from [another example](http://eclr.humanities.manchester.ac.uk/index.php/R_robust_se). It would be super useful if one could just pass a ``robust=TRUE`` parameter to ``sjt.lm()`` and it displays the adjusted values.

**Comment by sjPlot** [comment]
Ok, I added a `robust()` function to sjstats, that will compute robust se and ci, and also optionally exponentiate the estimates and ci if the fitted model is of type glm.

And, I added a `robust`-argument to both `sjt.lm()` and `sjt.glm()` of sjPlot, so robust se and ci can be shown in the table as well. Will commit changes tonight.

**Comment by cschwem2er** [comment]
Awesome! Thank you :)
