### ISSUE TITLE
adding `apaTables` package to `sjstats` imports

### ISSUE THREAD

**Issue by IndrajeetPatil** [sjPlot/sjstats#35]
I am wondering if there is any particular reason why `sjstats` is not importing `apaTables` package. The `sjstats` relies on it to compute confidence intervals for partial eta-squared and I am guessing you don't want to import the whole package just for one function?

I am asking because my package `ggstatsplot` (https://indrajeetpatil.github.io/ggstatsplot/) imports `sjstats` and it's having problems passing `R CMD CHECK` because the build keeps failing with the error:
```
Warning: Package `apaTables` needed to compute confidence intervals. 
Please install that package first.
```

The only way I can get around this issue is by importing literally every package `apaTable` relies on, which is not a very promising solution because no function from any of these packages appear in my `NAMESPACE`. Otherwise, I will just have to remove `sjstats` from dependencies and find other ways to compute 95% CI for partial omega- and eta-squared and that prospect is not very promising either. 

It would be awesome if you can add `apaTables` to your imports, so not just me but any other package that relies on `sjstats` will not have any such problems.

**Comment by strengejacke** [comment]
Yes, it's just one function, and - from my perspective - not a core-function, so I just conditionally require that package. I don't think that other packages that import sjstats do need apaTables as well. sjstats is imported by ggeffects and sjPlot, and neither has problems passing the checks.

**Comment by IndrajeetPatil** [comment]
@strengejacke I think that's because you comment out the examples which involve any reliance on `apaTables`. I never do so since I want `R CMD CHECK` to check all my examples. 

https://github.com/strengejacke/sjstats/blob/6e13954cc2d3c28ef66ed7017618d73863c2d811/R/eta_sq.R#L50-L55

Also, as pointed our by Thomas Leeper on Twitter, the new CRAN policy doesn't allow you to include `don't run` snippets, although this isn't reflected in their documents yet. For example, the policy (https://cran.r-project.org/web/packages/policies.html) still says-

> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms.

**Comment by strengejacke** [comment]
No, I think it might be that you're calling a function of sjstats that requires the apaTables package. This throws a warning, however, CRAN has all packages installed and checks should not fail here. You don't need to import apaTables. Just check with `devtools::build_win()`.

**Comment by IndrajeetPatil** [comment]
Yeah, I have a lot of examples in `.Rd` files and `vignettes` where I am calling the eta and omega-squared functions from `sjstats`. 

But it's all good now. I found a way around:
I'm now importing both `apaTables` and `MBESS` and that solves the problem. 

I personally don't like to leave it to the user to download any of the needed packages and tend to make them download all of them so that they never encounter a situation where they run a function and it throws an error because the needed package is not loaded. 

Btw, are you planning to release the next version of `sjstats` any time soon? I can probably wait to push the new version of my package to CRAN in that case.

**Comment by strengejacke** [comment]
Users don't get an error when they have not installed apaTables, it's just a warning. So everything is fine, and I would not import apaTables unless you use any function directly in your package (else, I think it would go even into DEPENDS?).

I'm planning a new update this month, but more towards the end of July. Due to the error in MBESS, I needed to submit my package three times within one week, so I need to reduce my update frequency for some time now.

**Comment by strengejacke** [comment]
Just a short note: Having packages in IMPORT or SUGGEST, which are not used in the package, indeed lead to problems in the check results. CRAN checks on Linux systems complain about suggested/imported packages that are not used.

**Comment by IndrajeetPatil** [comment]
![image](https://user-images.githubusercontent.com/11330453/42296366-0833de5e-7fc3-11e8-8f15-5fb500da3a43.png)

Yeah, I don't see any other solution. 

The problem is that a lot of my functions use outputs from `sjstats` functions somewhere in the middle of piped operations and if the `sjstats` function doesn't work (e.g., because the `apaTables` package is not available), then the entire function in my package fails and then of course `R CMD CHECK` produces error.

**Comment by strengejacke** [comment]
This should be no problem for CRAN, as they have all packages installed. It just stops, when the user doesn't have the packages.
To run tests locally, you need to install the packages as well, and remove them from the imports, as you don't use them in your package directly.

**Comment by strengejacke** [comment]
I could also check the licence of the packages and just copy the code for CI computation, so I don't need to depend on them.

**Comment by strengejacke** [comment]
I adapted and slightly modified the code from pkgs MBESS and apaTable, so these pkg are no longer required for sjstats. Will commit to GitHub later.

I think this is the most elegant solution, so you don't need any ugly workarounds.

**Comment by IndrajeetPatil** [comment]
Thank you so much, Daniel. Also, `ggstatsplot` has made it to CRAN with the other solution. :)
