### ISSUE TITLE
 conf.high lower than the partial.etasq

### ISSUE THREAD

**Issue by theogeneserich** [sjPlot/sjstats#39]
Dear all,

I am a bit confused about a result I am getting as Output of:

`model1 <- aov(Rating ~ (repfac1*repfac2) + Error(vid/(repfac1*repfac2)), contrasts = contr.sum, data = data_repeated_measure)`
`sjstats::eta_sq(model1, partial = TRUE, ci.lvl = .95)`
it gives me a partial.etasq of 0.955, conf.low of 0,193 and conf.high of 0.501.
My confusion is, because the conf.high is lower than the partial.etasq for that effect.

I get the same results for the CI when I use another R-package (MBESS):

`Lims <- conf.limits.ncf(F.value = 15.4105982, conf.level = 0.95, df.1 <- 3, df.2 <- 75)`
`Lower.lim <- Lims$Lower.Limit/(Lims$Lower.Limit + df.1 + df.2 + 1)`
`Upper.lim <- Lims$Upper.Limit/(Lims$Upper.Limit + df.1 + df.2 + 1)` 

Further I get an error message when trying to calculate the confidence interval for partial=FALSE:

`sjstats::eta_sq(model1, partial = FALSE, ci.lvl = .95)`

> "Error in cbind_all(x) : Argument 2 must be length 6, not 13"

Can you help me out here?
Thanks in advance!

**Comment by strengejacke** [comment]
Do you have a reproducible example for the second issue?

**Comment by theogeneserich** [comment]
Here the respective Code. Sry for the long vector at the beginning...
The Problem occurs for the main effect of repfac1.
Help is appreciated very much! 


`outcome= c(58,56,82,82,59,61,64,54,65,61,60,60,48,57,86,80,55,39,76,77,28,27,25,29,57,53,66,64,23,22,67,63,67,57,76,76,74,77,47,47,45,42,61,49,72,74,75,87,40,41,70,71,46,59,87,87,83,84,78,61,67,64,72,75,56,63,99,92,55,41,78,78,7,10,52,53,73,70,71,69,37,31,76,70,66,54,86,88,73,77,57,58,61,56,67,63,77,75,81,89,44,42,84,82,28,55,76,79,64,69,9,14,64,63,2,1,35,50,4,4,17,15,24,34,2,6,4,3,19,15,66,62,18,18,40,49,40,33,47,57,28,40,37,48,36,41,6,16,30,38,61,67,35,32,50,62,87,65,94,95,92,94,98,98,79,68,82,82,27,36,14,15,56,52,88,88,45,61,20,21,36,30,78,71,58,54,10,6,92,90,98,98,87,89,39,46,15,41,66,65,98,98,15,23,88,88,90,91)`

`data_repeated_measure = data.frame(repfac1=as.factor(rep(1:4, each=52)),`
                                  ` repfac2=as.factor(rep(c(1,2), 104)),`
                                  ` vid=as.factor(rep(rep(1:26, each=2), 4)),`
                                   `outcome=outcome)`

`options(contrasts = c("contr.sum","contr.poly"))`
`model1<- aov(outcome ~ (repfac1*repfac2) + Error(vid/(repfac1*repfac2)), contrasts = contr.sum, data=data_repeated_measure)`
`sjstats::eta_sq(model1, partial = T, ci.lvl = .95)`

**Comment by theogeneserich** [comment]
using:
`sjstats::eta_sq(model1, partial = F, ci.lvl = .95)`
gives the following error message (see above):

> Error in cbind_all(x) : Argument 2 must be length 6, not 13

**Comment by strengejacke** [comment]
closing, please use `effectsize::eta_squared()` (from [effectsize](https://easystats.github.io/effectsize/):

``` r
outcome= c(58,56,82,82,59,61,64,54,65,61,60,60,48,57,86,80,55,39,76,77,28,27,25,29,57,53,66,64,23,22,67,63,67,57,76,76,74,77,47,47,45,42,61,49,72,74,75,87,40,41,70,71,46,59,87,87,83,84,78,61,67,64,72,75,56,63,99,92,55,41,78,78,7,10,52,53,73,70,71,69,37,31,76,70,66,54,86,88,73,77,57,58,61,56,67,63,77,75,81,89,44,42,84,82,28,55,76,79,64,69,9,14,64,63,2,1,35,50,4,4,17,15,24,34,2,6,4,3,19,15,66,62,18,18,40,49,40,33,47,57,28,40,37,48,36,41,6,16,30,38,61,67,35,32,50,62,87,65,94,95,92,94,98,98,79,68,82,82,27,36,14,15,56,52,88,88,45,61,20,21,36,30,78,71,58,54,10,6,92,90,98,98,87,89,39,46,15,41,66,65,98,98,15,23,88,88,90,91)

data_repeated_measure = data.frame(repfac1=as.factor(rep(1:4, each=52)),
                                   repfac2=as.factor(rep(c(1,2), 104)),
                                   vid=as.factor(rep(rep(1:26, each=2), 4)),
                                   outcome=outcome)

options(contrasts = c("contr.sum","contr.poly"))
model1<- aov(outcome ~ (repfac1*repfac2) + Error(vid/(repfac1*repfac2)), contrasts = contr.sum, data=data_repeated_measure)
#> Warning in model.matrix.default(Terms, mf, contrasts): non-list contrasts
#> argument ignored

effectsize::eta_squared(model1, ci = .95)
#> Group               |       Parameter | Eta_Sq_partial |       95% CI
#> ---------------------------------------------------------------------
#> vid:repfac1         |         repfac1 |           0.38 | [0.20, 0.51]
#> vid:repfac1:repfac2 | repfac1:repfac2 |           0.20 | [0.05, 0.34]
#> vid:repfac2         |         repfac2 |           0.01 | [0.00, 0.21]
```

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
