### ISSUE TITLE
Nittiest of nitpicks: Name of chi-squared statistic in tables

### ISSUE THREAD

**Issue by jemus42** [sjPlot/sjstats#4]
I don't like the long name "`Chi-squared`" and would prefer a more accurate (and shorter) name.

Suggested replacement:

- Using unicode: 𝜒²
- Using HTML: `&chi;<sup>2</sup>`

[Would affect this line](https://github.com/sjPlot/sjstats/blob/master/R/xtab_statistics.R#L141)

This could also apply to other summary statistics in the table functions, but since all of these recently changed from "correct" symbols to ASCII-names, I assume there's a reson for the change, so this might be a pointless issue.

**Comment by sjPlot** [comment]
There is no specific reason, it is just the console-output that requires simple ASCII. I can add an additional attribute with HTML-usable names.

**Comment by sjPlot** [comment]
Basically, there are just 4 names to set: Chi, rho, tau and r - or am I missing something?

**Comment by sjPlot** [comment]
No, it's just the Chi2-value... Do you want the _estimate_ or the _statistics_ in HTML?
