### ISSUE TITLE
Tweedie r2

### ISSUE THREAD

**Issue by mebrooks** [sjPlot/sjstats#46]
Would it be possible to calculate an R2 value of models with the Tweedie distribution fit via glmmTMB? I found a worked example using cpglmm in [Nakagawa, Johnson, and Schielzeth 2017 Appendix s6](http://rsif.royalsocietypublishing.org/content/royinterface/suppl/2017/09/11/rsif.2017.0213.DC1/rsif20170213supp2.pdf). Is there anything particular that is missing from glmmTMB?

**Comment by mebrooks** [comment]
Sorry, I see now that to replicate the example linked above, glmmTMB needs `VarCorr` to work for the Tweedie and underlying that is the issue that we need to calculate the variance. I'll work on the variance part for now.

**Comment by strengejacke** [comment]
I saw you are submitting an update of glmmTMB to CRAN - is this issue addressed (i.e. do you have `VarCorr` for Tweedie now)?

**Comment by mebrooks** [comment]
Sorry, we didn't have time yet. I hope to do it in the next few months.

**Comment by strengejacke** [comment]
Ok, no hurry. Just asking because I'm planning to submit an update in January, and I would have tried to address this issue before submission if this had already gone into glmmTMB.

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/insight/issues/68
