### ISSUE TITLE
Loo-adjusted R2 warning: In ypredloo - y :   longer object length is not a multiple of shorter object length

### ISSUE THREAD

**Issue by DominiqueMakowski** [sjPlot/sjstats#50]
I have the following warning when extracting loo adjusted r2. Any idea why? Thanks a lot 😃 
```
Warning message:
In ypredloo - y :
  longer object length is not a multiple of shorter object length
```
The [data](https://github.com/strengejacke/sjstats/files/2562752/df.txt) is attached and the code is the  following:
```
library(rstanarm)

df <- read.table("df.txt")
fit <- stan_lmer(y ~ group / poly(x, 2) +
                   (1|r1) + (1|r2),
                 data=df, seed=6, QR=TRUE)
sjstats::r2(fit, loo=TRUE)
```

**Comment by strengejacke** [comment]
Should be fixed, though I'm not sure why there's a difference between the lengh of `y` (values from the response) and the length of `ypredloo` (the predicted values for the response). Maybe it's not possible to predict all values for the response properly in your model?

**Comment by strengejacke** [comment]
``` r
ncol(posterior_linpred(fit))
#> [1] 3963
```
