### ISSUE TITLE
Should there a vector version of equi_test?

### ISSUE THREAD

**Issue by Ax3man** [sjPlot/sjstats#56]
`rope` and `hdi` can take either models or vectors as input. I think it could be nice to also have a vector version for the `equi_test`. There is already a default method, but it is per definition non-functional. It is seemingly correctly calling `equi_test_worker`:

```
sjstats:::equi_test.default
function (x, rope, eff_size, out = c("txt", "viewer", "browser", 
    "plot"), ...) 
{
    out <- match.arg(out)
    equi_test_worker(x = x, rope = rope, eff_size = eff_size, 
        out = out, fm = NULL, ...)
}
```
But the first line of `equi_test_worker` checks this:

    if (fm$is_multivariate)

which will always fail with `fm = NULL`, as is done by the default method.

Not sure what the preferred solution is. Should `equi_test_worker` actually check for a `NULL` value for `fm`?

I'm currently using this simple version, that assumes a response variable with unit variance:
```
equi_test_vector <- function(x, rope = c(-0.1, 0.1), prob = .95) {
  .hdi <- sjstats::hdi(x, prop = prop)
  .rope <- sjstats::rope(x, rope)
  dplyr::case_when(
    .hdi[1] > rope[2] ~ "reject",
    .hdi[2] < rope[1] ~ "reject",
    .hdi[1] >= rope[1] & .hdi[2] <= rope[2] ~ "accept",
    TRUE ~ "undecided"
  )
}
```

Thanks for implementing ROPEs and the equi tests!

**Comment by strengejacke** [comment]
> Not sure what the preferred solution is. Should equi_test_worker actually check for a NULL value for fm?

Not sure either. What distribution should be assumed for vectors by default?

**Comment by Ax3man** [comment]
Ah good point! Gaussian I guess, with an argument to change that if possible.

**Comment by strengejacke** [comment]
Closing in favour of the development of the bayestestR package. We are setting up a new project (_easystats_), which will contains different packages for easily doing statistical computations in R. The Bayes-related functions go into the bayestestR pkg (https://github.com/easystats/bayestestR), and the `equivalence_test()` already has a vector version.
