### ISSUE TITLE
R2 MLM

### ISSUE THREAD

**Issue by DominiqueMakowski** [sjPlot/sjstats#65]
Dear Daniel, thanks a lot for your great suite of packages and their documentation, which helped me a ***lot*** in my own learning of stats and programming 😉 

I recently stumbled upon [this blogpost](https://mgb-research.netlify.com/post/visualizing-variance-in-multilevel-models-using-the-riverplot-package/) using a newly (again!) developed R2 measure for mixed models ([Rights & Sterba, 2018](https://s3.amazonaws.com/vu-my/wp-content/uploads/sites/2149/2016/07/21141635/RightsSterba2018_MLMR2.pdf); [Rights & Cole, 2018](http://sci-hub.tw/https://www.tandfonline.com/doi/abs/10.1080/15374416.2018.1528550?journalCode=hcap20)). However, the [function](https://s3.amazonaws.com/vu-my/wp-content/uploads/sites/2149/2018/06/20124816/r2MLM_codeandinput.txt) is a bit clunky to say the least, and relatively difficult to use due to the need of manual extraction of relevant indices. 

I have the feeling that it would be possible to re-implement it in a more digest way (i.e., that would automatically extract the things it needs from models). Unfortunately, my knowledge and understanding 
 of the internals of mixed models appears as unsufficient to be sure of that. What is your opinion? Do you think it would be worth it trying to re-implement this R2 framework? 

Again, thanks a lot 😊

**Comment by strengejacke** [comment]
Hi Dominique, I'm not quite sure what `r2mlm()` exactly does. It looks like extracting random effect variances. Is it similar to `sjstats::re_var()`?

**Comment by DominiqueMakowski** [comment]
Well, from the [table 2 of Rights & Cole 2018](http://sci-hub.tw/https://www.tandfonline.com/doi/abs/10.1080/15374416.2018.1528550?journalCode=hcap20) it seems as if the authors propose a more general (and extended) framework than the decomposition of Aguinis, or Nakagawa or such. From what I understood their indices (extracted with the r2mlm function) include and cover all the previously described indices of R², which sole report is deemed by the authors as insufficient.

They seem to suggest that their R2 framework would be a unifying answer to the "R2 for mixed models" controversy...

This [blogpost](https://mgb-research.netlify.com/post/visualizing-variance-in-multilevel-models-using-the-riverplot-package/) uses it with a brms model.

**Comment by strengejacke** [comment]
Closing in favour of https://github.com/easystats/performance/issues/2
