### ISSUE TITLE
r2 difference between two models?

### ISSUE THREAD

**Issue by hauselin** [sjPlot/sjstats#67]
Hi Daniel, thanks for creating this amazing package! Wonder if it'd make sense to create a new function, or extend your existing `r2()` function such that it can take two models at once (see example below), and then return the difference in r2 values of the two models? I'd assume people regularly take the difference in r2 values between two models to see whether adding new predictor(s) lead to better model fit? Thanks! 

```
m1 <- lm(mpg ~ qsec, mtcars)
m2 <- lm(mpg ~ cyl + qsec, mtcars)

# extend existing function
r2(m1, m2) # m2 r2 minus m1 r2

# or new function?
r2_diff(m1, m2) # m2 r2 minus m1 r2
```

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/performance/issues/28
