### ISSUE TITLE
feature request: confidence intervals for `cramer` and `phi`

### ISSUE THREAD

**Issue by IndrajeetPatil** [sjPlot/sjstats#69]
Is it possible to add support for confidence intervals for Cramer's _V_ and _phi_ effect sizes for contingency table analyses, just like omega- and eta-squared?

**Comment by strengejacke** [comment]
Something like

```r
efc %>% 
  select(e16sex, c161sex) %>% 
  sjstats::bootstrap(1000) %>% 
  mutate(
    tables = lapply(strap, function(x) {
      dat <- as.data.frame(x)
      table(dat$e16sex, dat$c161sex)
    }),
    cramers = sapply(tables, function(x) cramer(x))
  ) %>% 
  boot_ci(cramers)
```

?

**Comment by IndrajeetPatil** [comment]
Yeah, that sounds about right!

**Comment by strengejacke** [comment]
I just see that would require some breaking changes in the function-design. I need the data for bootstrapping, currently `cramer()` requires the table-object.
