### ISSUE TITLE
Question abow how intra-class correlation using sjstats::icc() is calculated

### ISSUE THREAD

**Issue by jrosen48** [sjPlot/sjstats#7]
#Thank you for a fantastic package. I have a quick question about how the intra-class correlation (ICC) using `sjstats::icc()` is calculated.

I have a fitted `lme4` model with the following error standard deviations:

- Random Effect A: 0.13
- Random Effect B: 0.59
- Random Effect C: 0.08
- Residual: 0.57

I would expect the ICC for Random Effect A to be: 0.13 / (0.13 + 0.59 + 0.08 + 0.57) = 0.094, however (as below) is 0.026. Similarly, I would expect the ICC for Random Effect B to be 0.59 / (0.13 + 0.59 + 0.08 + 0.57) = 0.43, however it is 0.49, and the ICC for Random Effect C to be 0.08 / (0.13 + 0.59 + 0.08 + 0.57) = 0.058, but it is 0.009. Can you help me understand why these are different?

```
> sjstats::icc(m1)
Linear mixed model
 Family: gaussian (identity)
Formula: overall_engagement ~ 1 + (1 | participant_ID) + (1 | program_ID/response_date_b)

  ICC (Random Effect A): 0.026098
  ICC (Random Effect B): 0.498624
  ICC (Random Effect C): 0.009448
```

**Comment by jrosen48** [comment]
Of course, the problem was using the error standard deviations, rather than the error variances. The output (of course) from sjstats::icc() is correct when I use the variances. Sorry about that.

**Comment by strengejacke** [comment]
Ok, so can I close this issue?

**Comment by jrosen48** [comment]
Yep. Thank you
