### ISSUE TITLE
why use omega squared and not epsilon squared?

### ISSUE THREAD

**Issue by ntraut** [sjPlot/sjstats#71]
It is now recognized that both omega squared and epsilon squared are (littlely) downward biased, but omega squared is sensibly more biased than epsilon squared:
- [Why you should use omega-squared instead of eta-squared.](http://daniellakens.blogspot.com/2015/06/why-you-should-use-omega-squared.html)
- [IS OMEGA SQUARED LESS BIASED? A COMPARISON OF THREE MAJOR EFFECT SIZE INDICES IN ONE-WAY ANOVA](https://www.jstage.jst.go.jp/article/bhmk/40/2/40_129/_article) (figure 1)

So I wonder why not support epsilon squared rather than omega squared if it is less biased?

**Comment by strengejacke** [comment]
I usually never use these effect sizes, so I only implemented them by demand. Since there was no request for epsilon squared (until now), it's not yet implemented.

I'll see if it's easy to add to the package...
