### ISSUE TITLE
mwu for more than 2 groups gives wrong effect-size `r`

### ISSUE THREAD

**Issue by maxgav13** [sjPlot/sjstats#83]
Hi

It seems that when using the `mwu` function for more than 2 groups the effect size `r` is incorrect, since the formula is Z/sqrt(N), it looks like you are using the same N for all the comparisons as the total sample size, instead of using the N for each comparison. Let's say n1=4, n2=3, n3=5, N=12, the effect sizes you report all use N and not n1+n2, n1+n3, n2+n3, which might be more appropriate

Regards and thanks for this great package

**Comment by strengejacke** [comment]
thanks, fixed!
