### ISSUE TITLE
Minor issue with R Notebooks

### ISSUE THREAD

**Issue by VectorPosse** [sjPlot/sjstats#84]
Many of the commands in this package produce a "header" of sorts in their output. For example, the `hdi` function has output labeled with

```
# Highest Density Interval
```

But this breaks up the output in the R Notebook into two windows because one is writing to the Console and the other is printing a data frame.

It's only a minor annoyance, but I'm wondering if there could be a way to turn off that header.

**Comment by strengejacke** [comment]
Do you have a reproducible example? I'm not quite sure which problem you have.

**Comment by VectorPosse** [comment]
Well, I just tried it again and it seems to work okay now. Maybe RStudio changed the way the R Notebooks render output so that it all appears together instead of breaking the output apart into two pieces. Or maybe something changed on your end in the print method. Not sure. Either way, it looks fine for now, so I'll close this issue. Thanks for responding.
