### ISSUE TITLE
Changes to r2() function?

### ISSUE THREAD

**Issue by awhug** [sjPlot/sjstats#85]
Hi Daniel,

Thanks very much for the very helpful 'sjstats' package. Just writing to get some more info on changes to the r2() function. 

I used this function in April last year with a particular dataset, which at the time yielded an R^2 estimate of 0.3233. Running it today, I get entirely different values (Marginal = .131, Conditional = .254). I understand this function was updated in July of 2018 - what specifically changed in the calculation, and why was this implemented? Should my previous estimate be regarded as incorrect?

Cheers!

**Comment by strengejacke** [comment]
What kind of models are you referring to? I assume mixed models, probably lme4?

**Comment by strengejacke** [comment]
In general, I would not say "incorrect", as R2 for more complex models are always some kind of approximation.

The "new" R2 function is based on extracting variances for different distributional families / models, and those functions have been re-implemented and improved in the _insight_ package. See details and references here:

https://easystats.github.io/insight/reference/get_variance.html

Note that from the next update, many model-related functions are deprecated and re-implemented in different packages from the [easystats-project](https://github.com/easystats/easystats).

The R2-function is implemented in the _performance_ package: https://easystats.github.io/performance/reference/r2.html, which - for mixed models- internally calls [r2_nakagawa()](https://easystats.github.io/performance/reference/r2_nakagawa.html). That is the most current "state of the art" of computing R2 values for mixed models.

**Comment by awhug** [comment]
> What kind of models are you referring to? I assume mixed models, probably lme4?

Sorry! Should have specified - yes, this is a standard lme4 lmer() model, of the form: 

`lmer(y ~ fixed_factor_a + ( fixed_factor_a | random_factor_a ), data)`

> In general, I would not say "incorrect", as R2 for more complex models are always some kind of approximation.
> 
> The "new" R2 function is based on extracting variances for different distributional families / models, and those functions have been re-implemented and improved in the _insight_ package. See details and references here:
> 
> https://easystats.github.io/insight/reference/get_variance.html
> 
> Note that from the next update, many model-related functions are deprecated and re-implemented in different packages from the [easystats-project](https://github.com/easystats/easystats).
> 
> The R2-function is implemented in the _performance_ package: https://easystats.github.io/performance/reference/r2.html, which - for mixed models- internally calls [r2_nakagawa()](https://easystats.github.io/performance/reference/r2_nakagawa.html). That is the most current "state of the art" of computing R2 values for mixed models.

Ok, this is useful info! Good to know different versions available in the 'performance' package.

After doing some googling, it appears the previous implementation of r2() in 'sjstats' for lme4 models prior to mid-2018 was based on the correlation between fitted and observed values, as apparently first described [here](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2008q2/000714.html) by Jarrett Byrnes and outlined as a 'simple/crude solution' under the [GLMM FAQ document](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#simplecrude-solutions). 

I tried running the r2_xu() method, but the results were slightly off. However running this Byrnes function sourced from the GLMM FAQ document above did work:

`r2.corr.mer <- function(m) {
   lmfit <-  lm(model.response(model.frame(m)) ~ fitted(m))
   summary(lmfit)$r.squared
}`

This replicated my previous R^2 result (0.3233) from last year, as well as other R^2 from different model variants at the time. 

Unless this info is inaccurate, happy to have the issue closed now! Thanks for the prompt response.

**Comment by strengejacke** [comment]
If you need to replicate your result, I suggest using Byrnes function, else, if you can revise your results, I suggest using `r2_nakagawa()`.

Some functions will in _sjstats_ that moved to other packages will simply be re-exported, so there's no difference from a user's perspective. Other _sjstats_ functions will throw a deprecated-warning and then call the new functions automatically.
