### ISSUE TITLE
tidy_stan() error with multivariate brms models

### ISSUE THREAD

**Issue by lnalborczyk** [sjPlot/sjstats#94]
Hi,

Just for information, I have recently updated the `sjstats` package and the `sjstats::tidy_stan()` function now throws an error when applied to multivariate `brms` models: `Error: Currently, estimating 'rescor' is only possible in multivariate gaussian or student models.`

EDIT: the bug seems to come from the last version of `brms` (2.9.0), downgrading to `brms` 2.8.0 removed this error...

Ladislas

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by lnalborczyk** [comment]
Hi, sorry for the late reply.

False alarm, I can not reproduce the error using the latest version of `brms`. I think this issue can be closed. My apologies for the inconvenience.

**Comment by strengejacke** [comment]
Thanks!
