### ISSUE TITLE
se() works only when lmer () contains correlation parameters

### ISSUE THREAD

**Issue by HirokiYamamoto2531** [sjPlot/sjstats#95]
Hi,

I am now using se() to get SEs of coefficients.
When I fit the model with correlation parameters like below , se() successfully works.

model <- lmer(rt ~ 
                   a + 
                   (1  + a | subject),
                 data = data)

se(model)

However, when I removed correlation parameters like below, I get an error message.

model <- lmer(rt ~ 
                   a + 
                   (1  + a | |subject),
                 data = data)

se(model)

Does anyone know why?

Thank you

**Comment by strengejacke** [comment]
There is a new project, [easystats](https://github.com/easystats), where we collaborate on a set of packages that are newly designed from scratch, trying to make statistical analyses (in particular with model objects) easier. Therefore, some of my packages here (mostly _sjstats_) are redesigned resp. part of the functions are re-implemented in the easystats-packages.

You may use [`parameters::standard_error()`](https://easystats.github.io/parameters/reference/standard_error.html), which seems to work with your models:

``` r
library(lme4)

m <- lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)
parameters::standard_error(m)
#>     Parameter       SE
#> 1 (Intercept) 6.823773
#> 2        Days 1.545958

m <- lmer(Reaction ~ Days + (1 + Days || Subject), data = sleepstudy)
parameters::standard_error(m)
#>     Parameter       SE
#> 1 (Intercept) 6.885097
#> 2        Days 1.559668
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by HirokiYamamoto2531** [comment]
Hi,

Thank you for the reply.

It works when you try to get fixed effects, irrespective of correlation parameters; e.g., 

m <- lmer(Reaction ~ Days + (1 + Days || Subject), data = sleepstudy)
parameters::standard_error(m, effects = c("fixed"))

#  Parameter       SE
#1 (Intercept) 6.885097
#2        Days 1.559668

However, when you try to get random effects for each subject, standard_error () works only when the model includes correlation parameters; thus the following does not work:

m <- lmer(Reaction ~ Days + (1 + Days || Subject), data = sleepstudy)
parameters::standard_error(m, effects = c("random"))

Error in array(NA, c(J, K)) : 'dims' cannot be of length 0

Do I miss something?

Thank you

**Comment by strengejacke** [comment]
moved to here:
https://github.com/easystats/parameters/issues/202
